name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/964512664154/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'ais-gemini-key-fcf8aec67b8c433@964512664154.iam.gserviceaccount.com'

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy golf-ai-app \
            --image gcr.io/964512664154/my-image \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated
